[default.http]
# DIDKIT_HTTP_HTTP_PORT
port = 3000
# DIDKIT_HTTP_HTTP_ADDRESS
address = [127, 0, 0, 1]
# DIDKIT_HTTP_HTTP_BODYSIZELIMIT
bodysizelimit = 2097152 # 2MiB

[default.issuer]
# DIDKIT_HTTP_ISSUER_KEYS
# keys = '[<JWK>, <JWK>]'
# DIDKIT_HTTP_ISSUER_BASEURL
# base_url = "http://127.0.0.1:3000/"

[test.issuer]
base_url = "http://127.0.0.1:3000/"
