name: ci

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: Swatinem/rust-cache@v2

    - name: Build
      run: cargo build
    - name: Test
      run: cargo test
    - name: Clippy
      run: cargo clippy

  vc_api_test_suites:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        suite:
          # - "vc-api-issuer-test-suite" # not updated to latest test suites config
          # - "vc-api-verifier-test-suite" # not updated to latest test suites config
          - "vc-di-ecdsa-test-suite"
          - "vc-di-eddsa-test-suite"
          - "vc-di-ed25519signature2020-test-suite"
          # - "did-key-test-suite" # not updated to latest test suites config
          # - "vc-data-model-2.0-test-suite" # new tests were added to VPs which are failing
          - "vc-di-bbs-test-suite"
          - "vc-bitstring-status-list-test-suite"
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: Swatinem/rust-cache@v2
      with:
        shared-key: "vc-api"
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Start VC API
      run: |
        cargo build
        export DIDKIT_HTTP_ISSUER_KEYS='[{"kty":"OKP","crv":"Ed25519","x":"HvjBEw94RHAh9KkiD385aYZNxGkxIkwBcrLBY5Z7Koo","d":"1onWu34oC29Y09qCRl0aD2FOp5y5obTqHZxQQRT3-bs"}, {"kty":"EC","crv":"P-256","x":"c01opxmxLeRMYhyTaiOKzvOF6DDjEajzb968ClJWB9Q","y":"oM3B1R0J-Cynleb00D-PManSGnlltcgsMJaoPbPOewU","d":"g-jUBRnfkbsxOQhtrBZd9l_ElOAw8BoJufTFUut2uHI"}, {"kty":"EC","crv":"P-384","x":"G09OCsHnoen7IWnA9ETEKl7NmPwakpHo9KOH5bUB2nJzyn5Zco-qqBchqUi1-uaz","y":"_CtCA3SUZS4IEOJN999aLTEIQOOWOX9biXqbFs4OCa1OMvjoVzzC2BimVnHrrcQ7","d":"qCiwiC8sASQ3chYPN8BodDImdVbn-didbDeQdQAnGJYoRWryN3xF1xX96w6SJTx6"}, {"kty":"EC","crv":"BLS12381G2","x":"Fln1NOjRnBckd2iuVZNmR7Agg0KyHt2NbyGEdnEJ-oeWtLP5oAjo97jwlT760SJNBoxjZAsqNkROO6iYbBlOT2ThVHfT9M12YyG63jO1WJExHxdvR9A_epWMaBPXIjrk","y":"DqCv2qtjzoMdjoh2vdLV82L8AW1-Um6auYtoyME2tBWuqvJBVJpre5Ok63iUQ2PhFMlzUsJ8mgShh3XHsyW-3NNVJfgM70sNHkjwW4Y8cUXiKgHBpXMr_Wy9syNYbyWw","d":"TLmBUbKXS_62DsgQHBdOJQx1vr6FKF8O86iAmkQZHgQ"}]'
        export DIDKIT_HTTP_ISSUER_BASEURL="https://127.0.0.1:9000/"
        cargo run &
    - name: Start HTTPS Proxy
      run: npx local-ssl-proxy --source 9000 --target 3000 --hostname 127.0.0.1 &
    - name: Setup Test Suite
      run: |
        cd tests/${{ matrix.suite }}
        npm i
        ln ../localConfig.cjs localConfig.cjs
    - name: Run Test Suite
      run: |
        cd tests/${{ matrix.suite }}
        npm test
